events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    upstream flask_app {
        server flask:8000;
    }

    # Основной сервер на порту 8
    server {
        listen 80;
        server_name localhost;

        location / {
            proxy_pass http://flask_app;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /health {
            proxy_pass http://flask_app/health;
            access_log off;
        }
    }

    # Сервер для метрик на порту 81
    server {
        listen 81;
        server_name localhost;

        location /nginx_status {
            stub_status on;
            access_log off;
            allow 127.0.0.1;
            allow 172.16.0.0/12;  # разрешаем доступ из Docker-сети
            allow all;
        }
    }
}